### DISCUSSION TITLE
Langzeitstatistiken

### DISCUSSION THREAD

**Discussion by stefangrosse** [dewenni/ESP_Buderus_KM271#138] [Q&A]
Hi.

Ich habe ein Problem mit den Statistiken, was mir heute erst aufgefallen ist:

<img width="1309" alt="Bildschirmfoto 2024-12-30 um 11 25 05" src="https://github.com/user-attachments/assets/4122340a-bacf-49f0-af21-c1573f534206" />

Oben ist mein Ölverbrauch den ich aus der Brennerlaufzeit berechne. Die Brennerlaufzeit geht aber nur bis zum 20.12. zurück. Es wurde aber schon vorher der Verbrauch errechnet. Das ist bei allen Entitäten die von der Schnittstelle kommen so. 
Woran kann das liegen? Bin für jeden Tipp dankbar!

**Comment by stefangrosse** [comment]
In der Datenbank sind die States vorhanden:

<img width="783" alt="Bildschirmfoto 2024-12-30 um 11 54 16" src="https://github.com/user-attachments/assets/baaf7fbf-2e07-40cc-9d10-45312380f63e" />
<img width="892" alt="Bildschirmfoto 2024-12-30 um 11 55 45" src="https://github.com/user-attachments/assets/f237aa60-3185-4bc2-b7b5-2963289bc3a1" />

Es sind aber keine Statistiken vorhanden:
<img width="966" alt="Bildschirmfoto 2024-12-30 um 11 56 53" src="https://github.com/user-attachments/assets/8e188328-2ca2-4503-a889-0d3c20d885e0" />

Meine alten Sensordaten sind noch da (Vor der Umstellung auf Karte) :
<img width="1092" alt="Bildschirmfoto 2024-12-30 um 11 57 11" src="https://github.com/user-attachments/assets/6af2b181-f23d-4f4d-ad4f-4d9446ba59c5" />

**Comment by paxrsi** [comment]
Ich hatte das gleiche Problem. Die Sensordaten waren nur die letzten x Tage im Homeassistant vorhanden. So wie ich das verstanden habe ist die Ursache, dass Homeassistant zwei Datenbanken hat. Eine mit den vollständigen Daten für ein paar Tage. Danach werden die Daten in längere Zeiträume zusammengefasst in eine andere (Langzeit)-Datenbank übertragen. Dieser Übertrag fand bei mir bei den Logamatic-Daten nicht statt.

Ich habe das Problem bei mir wie folgt gelöst:

1.) Es gibt eine Einstellung, mit der man Homeassistant sagt, wie lange die Daten in der Kurzzeitdatenbank sein sollen. Die Einstellung kann man nur für alle Datenquellen universell angeben. D.h. die Größe der Datenbank wächst damit stark an. In der configuration.yaml habe ich dazu folgendes für 31 Tage aufgenommen:

```
recorder:
  purge_keep_days: 31
```

2.) Damit die Daten in die Langzeitdatenbank übertragen werden, habe ich eine weitere Anpassung in der configuration.yaml vorgenommen. Dazu habe ich mich an dem orientiert, was ich für meinen Stromverbrauchsmesser am Zählerkasten mal aufgenommen hatte. Was das genau tut und warum das funktioniert, kann ich dir leider auch nicht sagen. So tief stecke ich in Homeassistant nicht drin.

```
homeassistant:
  customize_glob:
   sensor.logamatic_oelverbrauch_gesamt_berechnet:
      state_class: measurement
      device_class: volume
      unit_of_measurement: "l"

    sensor.logamatic_aussentemperatur_gedaempft:
      state_class: measurement
      device_class: temperature 
      unit_of_measurement: "°C"
```
Ich hoffe, das hilft!

Keine Ahnung, ob man das dem Homeassistant schon bei der Erkennung der MQTT-Daten beibringen kann. Aber ehrlich gesagt, brauche ich die Langzeitspeicherung auch nicht für alles.

Edit: Ach ja, im Zweifel anschließend Homeassistant einmal durchstarten, damit die Änderungen sicher gezogen werden.


Grüße
Rainer

**Comment by stefangrosse** [comment]
Danke! Das hat mich auf den richtigen Weg gebracht. Es muss die richtige state_class gesetzt werden, damit eine Langzeitstatistik erstellt wird. Die Recordereinstellungen sind aus meiner Sicht nicht nötig, die sind im Standard 10 Tage (https://www.home-assistant.io/integrations/recorder/#purge_keep_days).

Hier wird es in Doku beschrieben:
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

Für den Sensor Brenner Laufzeit Summe ist keine state_class angegeben: 

<img width="940" alt="image" src="https://github.com/user-attachments/assets/6b735ec9-d07f-4c0d-bb71-b1042e4edc13" />

@dewenni Wäre es nicht sinnvoll das zu ergänzen? 

Ich probiere diese jetzt über:
```
homeassistant:
  customize:
    sensor.logamatic_brenner_laufzeit_summe:
      state_class: measurement
```

**Comment by dewenni** [comment]
ich kann `state_class: measurement` gerne in der Konfiguration ergänzen.
Wenn Ihr sonst noch Änderungsvorschläge bei der Konfiguration habt, dann stellt mir das gerne mal zusammen.
Ich bin zugegeben nicht der größte Home Assistant Experte und habe das nach bestem Wissen und Gewissen gemacht.
Also macht mir gerne eine Übersicht bei welchen Datenpunkten ich noch was ändern oder ergänzen sollte.

**Comment by stefangrosse** [comment]
Ich habe das für folgende noch ergänzt:

```
sensor.logamatic_brenner_laufzeit_summe:
    state_class: measurement
sensor.logamatic_brenner_ansteuerung:
    state_class: measurement
sensor.logamatic_brenner_einschalttemperatur:
    state_class: measurement
sensor.logamatic_brenner_ausschalttemperatur:  
    state_class: measurement
sensor.logamatic_hk1_heizkennlinie_10_grad_2:
    state_class: measurement
sensor.logamatic_hk1_heizkennlinie_0_grad:
    state_class: measurement
sensor.logamatic_hk1_heizkennlinie_10_grad:
    state_class: measurement
sensor.logamatic_kessel_vorlaufsolltemperatur:
    state_class: measurement
sensor.logamatic_kessel_vorlaufisttemperatur:
    state_class: measurement
sensor.logamatic_hk1_vorlaufsolltemperatur:
     state_class: measurement
sensor.logamatic_aussentemperatur:
     state_class: measurement
sensor.logamatic_ww_solltemperatur:
     state_class: measurement
sensor.logamatic_ww_isttemperatur:
     state_class: measurement
sensor.logamatic_hk1_raumsolltemperatur:
     state_class: measurement
sensor.logamatic_max_kesseltemperatur:
     state_class: measurement
sensor.logamatic_pumplogik:
     state_class: measurement
```
